### ISSUE TITLE
where is version 1.12.42 source?

### ISSUE THREAD

**Issue by ac427** [sysdiglabs/sysdig-operator#17]
The latest version on redhat openshift catlog is `1.12.42`, but the master branch version has `1.12.40`
https://github.com/sysdiglabs/sysdig-operator/blob/master/Makefile#L6
Did you miss bumping the version in the previous merge? Or is there some other repo from where the source comes from?

**Comment by achandras** [comment]
Hi @ac427 , we did indeed miss bumping the bundle version for 1.12.42. As of 1.12.44, the published and source bundle versions now match
